[package]
name = "dataweave"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
clap = { version = "4.0", features = ["derive"] }
